- hosts: localhost
  tasks:
    - package: 
       name: python-pip
       state: present
    - pip:
       name: docker-py
       state: present
    - docker_container:
       name: mydoc
       image: centos   
